ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS min_confidence NUMERIC NOT NULL DEFAULT 78,
ADD COLUMN IF NOT EXISTS daily_loss_limit_pct NUMERIC NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS max_consecutive_losses INTEGER NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS allow_trend_trades BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS allow_mean_reversion_trades BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE public.trades
ADD COLUMN IF NOT EXISTS setup_type TEXT,
ADD COLUMN IF NOT EXISTS entry_confidence NUMERIC,
ADD COLUMN IF NOT EXISTS trade_metadata JSONB;